"""changed schema

Revision ID: 1aaa44bb4953
Revises: d12cd7506581
Create Date: 2024-04-23 22:43:19.207047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1aaa44bb4953'
down_revision = 'd12cd7506581'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('travelplans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('destination', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('traveler_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['traveler_id'], ['travelers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('travel_plan')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('travel_plan',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('destination', sa.VARCHAR(length=100), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('travelplans')
    # ### end Alembic commands ###
