"""Added activity column to travelplan table

Revision ID: 96621c36aa02
Revises: bb039147f92f
Create Date: 2024-04-24 21:28:42.174667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96621c36aa02'
down_revision = 'bb039147f92f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('travelplans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activity', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('travelplans', schema=None) as batch_op:
        batch_op.drop_column('activity')

    # ### end Alembic commands ###
