"""added bio column to travelers table

Revision ID: a8fbe182d79f
Revises: ead955ddef2e
Create Date: 2024-04-24 04:11:21.768857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8fbe182d79f'
down_revision = 'ead955ddef2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('travelers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('travelers', schema=None) as batch_op:
        batch_op.drop_column('bio')

    # ### end Alembic commands ###
