"""added image field to traveler class

Revision ID: ead955ddef2e
Revises: 1aaa44bb4953
Create Date: 2024-04-23 22:57:47.947158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ead955ddef2e'
down_revision = '1aaa44bb4953'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('travelers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('travelers', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
